### ISSUE TITLE
Using this with interrupt

### ISSUE THREAD

**Issue by mm108** [alex-code/GT911#1]
hi, Thanks for the cool library. Just a quick question please - Is there an example on how to use the interrupts? Cheers.

**Comment by alex-code** [comment]
To use an interrupt you just need to specify an interrupt capable pin with `begin` then use the interrupt mode when checking for touches.
Enumerating through touches is same as the polling example.

```cpp
#include <Arduino.h>
#include <GT911.h>

GT911 ts = GT911();
const uint8_t INT_PIN = 1;

void setup() {
  Serial.begin(115200);
  ts.begin(INT_PIN);
}

void loop() {
  uint8_t touches = ts.touched(GT911_MODE_INTERRUPT);

  if (touches) {
    GTPoint* tp = ts.getPoints();
    for (uint8_t  i = 0; i < touches; i++) {
      Serial.printf("#%d  %d,%d s:%d\n", tp[i].trackId, tp[i].x, tp[i].y, tp[i].area);
    }
  }
}
```

**Comment by mm108** [comment]
Perfect, thanks Alex! Exactly what I was looking for. I was in the same situation - got a [DFR0669](https://wiki.dfrobot.com/3.5inches_480_320_TFT_LCD_Capacitive_Touchscreen_SKU_DFR0669) and wanted to use it with TFT_eSPI. Unfortunately TFT_eSPI supports only XPT2046 touch controllers. Your library seems to be a perfect fit. It works very well. Thanks once again. Cheers.

**Comment by alex-code** [comment]
Glad it's useful :)
I've got one of those displays too although I couldn't seem to get the interrupt to work so created the polling version.

**Comment by mm108** [comment]
The interrupt version - I have not been able to get that to work yet but the polling version works very well :) And that solves my problem. I will experiment with the interrupt version sometime soon. I'll post if I can get that to work. Cheers.

**Comment by mm108** [comment]
> Glad it's useful :) I've got one of those displays too although I couldn't seem to get the interrupt to work so created the polling version.

hi Alex,

While researching the (problem) with the interrupt version not working, I came across something that I thought I should share with you. It probably holds some pointers. The first problem that I see is that it may require the RST pin for Touch. Haven't tried to play with the code yet but I thought I'd share it with you. Cheers

[gt911.cpp](https://github.com/yeacreate-opensources/Nscreen_32/blob/1fc9c9846ee65e854c4726cc1d65a164ec51a59a/lvgl_demo/src/gt911.cpp)
[gt911.h](https://github.com/yeacreate-opensources/Nscreen_32/blob/1fc9c9846ee65e854c4726cc1d65a164ec51a59a/lvgl_demo/src/gt911.h)

**Comment by alex-code** [comment]
Hi, Thanks for having a look.
I think the problem here is the GT911 RST pin isn't broken out on the DFRobot display so it can't be used.

**Comment by mm108** [comment]
hi Alex,

Yes, it's pulled to the 3.3v with a 10k resistor. But thankfully your polling version works for me fine. 

![Touch_FPC](https://user-images.githubusercontent.com/10776430/181001314-19c4a057-26b8-4a68-aecc-3cb038557a2c.jpg)

[dfr0669-schematic.pdf](https://github.com/alex-code/GT911/files/9189555/dfr0669-schematic.pdf)

How I wish DFROBOT did a better job in terms of connections and provide some flexibility by making the RST available on the breakout.

Thanks Alex at least I can get going with your library. Hopefully I'll get some time soon to have a second look.

**Comment by alex-code** [comment]
> How I wish DFROBOT did a better job in terms of connections and provide some flexibility by making the RST available on the breakout.
> 

Same, I'd hoped to put the FireBeetle and display into low power modes but without access to the GT911 RST you can't wake it up :(

**Comment by mm108** [comment]
haiz! That board is not among the cheapest and then we have to deal with this :-D 

DFROBOT has this thing called the GDI interface on one of their ESP32 boards and I guess they expect people to be using one of their ESP32 boards which has the GDI interface / connector thereby making it easier to hook up their board whilst making it difficult for others :.)

![20220726_204022](https://user-images.githubusercontent.com/10776430/181052949-c55464cb-325b-40e0-9fa3-16876ac28c07.jpg)

~~I have a bunch of FPC connector/breakouts lying around. I have half a mind to try hooking that up and run the line to ESP32 for TP RST. But first I have to find out where I threw the damn FPC cables! lol~~

~~The way it is with the DFR0669 board, I am not 100% sure if the FPC board/cable solution will solve the problem but I hope/guess the 10k resistor won't cause an issue with the reset. Would the pin need to be directly pulled to the low or having the resistor in between should still work. Hmmm, I am more of a Software guy than an electronics guy. Cheers.~~

I guess the FPC breakout solution might not work because it seems like it's the other end of the line (that's connected to 3.3v) that's exposed and not the chip/pin.

**Comment by alex-code** [comment]
It looks like that breakout would work, there's only 6 connections for the GT911.

**Comment by mm108** [comment]
> It looks like that breakout would work, there's only 6 connections for the GT911.

The cable fits in nicely but I gota figure out where the R9 is. If it's on the main board, then problem solved as I would just need to run one line from the breakout to the ESP32. But If it is on that small cable ( with the Touch Controller ), then I am out of luck - that is unless I can toggle the "resistor(R9) + 3V3" to "resistor(R9) + GND" and back. The later sounds like a hack rather than a fix :) Cheers.

**Comment by alex-code** [comment]
I found someone using the same breakout as you with an Arduino Due, they just wired it straight up, http://www.digitaltown.co.uk/components14ESP32GT911Screen.php
Not got a multimeter to hand but looking at the traces on the board it looks like the RST goes to a 10k resistor on the DFRobot board.

**Comment by mm108** [comment]
Cool, thanks. It's the same board. Last time I got a bunch of those from AliExpress because I was trying to mod a cheap Chinese touch control lamp. Never thought one day those boards will come handy :) Cheers.
