### ISSUE TITLE
Include a minimal example

### ISSUE THREAD

**Issue by steviebuilds** [alex-code/GT911#4]
Hi Alex,

Thanks for putting this up.

I'm a bit out of my depth with this tech. I'm trying to get the same DFRobot capacitive touch screen working and came across similar issues to what a lot of people seem to be encountering - the INT pin not working.

I'm trying to get a minimal polling solution going with platformio, teensy 4.1. Essentially just what you have in the readme.

I get a few errors:
```
lib/GT911/GT911.cpp:93:19: error: '_min' was not declared in this scope; did you mean 'min'?
```

and

```
lib/GT911/GT911.cpp:93:38: error: 'I2C_BUFFER_LENGTH' was not declared in this scope; did you mean 'BUFFER_LENGTH'?
```

I tried changing to `min` and added `#define I2C_BUFFER_LENGTH 32` but get no printing in the serial monitor.

Would you be able to include a minimal example in the repo?

Thanks.

**Comment by alex-code** [comment]
Those changes you've made should work.
I've not compiled against a Teensy, will try and add in some defines.

If you try adding `Serial.println("test");` in `setup()` after `Serial.begin();` does that output?

If you can get that to output you could also try `Serial.println(ts.begin());` to see if that prints 1

**Comment by steviebuilds** [comment]
Yeah so the method doesn't exist (0). Makes me wonder if its referencing the class in the DFRobot_GT911.h file even though it links to your implementation.


<img width="1548" alt="Screenshot 2023-12-13 at 12 34 53" src="https://github.com/alex-code/GT911/assets/16717394/1a0e8190-448d-40b8-b494-c793b321127e">

**Comment by alex-code** [comment]
Did it print `test` in the serial monitor?
The DFRobot class shouldn't cause an issue.

Are you able to show your wiring?
Checking Teensy's site it says pins 18 & 19 are the default I2C pins on the 4.1

**Comment by steviebuilds** [comment]
Thank you! That led me to scrutinising the SDA and SCL, I tried swapping the cables and now I'm getting coordinates 🥲🔫

Thanks a bunch for your patience and help!
